const mongoose = require('mongoose');
require('dotenv').config({ path: '../.env' });
const Service = require('../models/Service');
const Product = require('../models/Product');

const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/nexoraindia';

const services = [
  { title: 'Web Development', slug: 'web-development', shortDescription: 'Modern, responsive websites and web applications built with latest technologies.', fullDescription: 'We craft stunning, high-performance web applications using cutting-edge technologies like React, Next.js, and Node.js. Our websites are mobile-first, SEO-optimized, and built for scale.', icon: 'FaCode', features: ['Responsive Design', 'SEO Optimized', 'Fast Loading', 'Custom CMS', 'E-commerce Solutions', 'Progressive Web Apps'], technologies: ['React', 'Next.js', 'Node.js', 'MongoDB', 'PostgreSQL', 'WordPress'], priceRange: 'Starting from Rs.25,000', deliveryTime: '2-8 weeks', category: 'Development', order: 1 },
  { title: 'Mobile App Development', slug: 'mobile-app-development', shortDescription: 'Cross-platform and native mobile apps for iOS and Android.', fullDescription: 'From concept to launch, we build powerful mobile applications that users love. We specialize in React Native for cross-platform development and Flutter for beautiful UI.', icon: 'FaMobile', features: ['iOS & Android', 'Cross-Platform', 'Push Notifications', 'Offline Support', 'App Store Deployment', 'UI/UX Design'], technologies: ['React Native', 'Flutter', 'Firebase', 'REST APIs', 'Swift', 'Kotlin'], priceRange: 'Starting from Rs.50,000', deliveryTime: '4-12 weeks', category: 'Development', order: 2 },
  { title: 'API Development', slug: 'api-development', shortDescription: 'Robust, scalable REST and GraphQL APIs for your business needs.', fullDescription: 'We design and develop secure, well-documented APIs that power your applications. From microservices to monolithic APIs, we handle authentication, rate limiting, and documentation.', icon: 'FaServer', features: ['REST & GraphQL', 'Authentication & JWT', 'Rate Limiting', 'API Documentation', 'Microservices', 'Third-party Integrations'], technologies: ['Node.js', 'Express', 'GraphQL', 'Swagger', 'Postman', 'Docker'], priceRange: 'Starting from Rs.20,000', deliveryTime: '1-4 weeks', category: 'Development', order: 3 },
  { title: 'DevOps & Cloud', slug: 'devops-cloud', shortDescription: 'CI/CD pipelines, cloud infrastructure, and deployment automation.', fullDescription: 'Streamline your development workflow with our DevOps expertise. We set up CI/CD pipelines, manage cloud infrastructure on AWS/GCP/Azure, and ensure your applications are always available.', icon: 'FaCloud', features: ['CI/CD Pipelines', 'Docker & Kubernetes', 'AWS/GCP/Azure', 'Monitoring & Alerts', 'Auto Scaling', 'Security Hardening'], technologies: ['AWS', 'GCP', 'Azure', 'Docker', 'Kubernetes', 'GitHub Actions'], priceRange: 'Starting from Rs.15,000/month', deliveryTime: '1-3 weeks setup', category: 'Infrastructure', order: 4 },
  { title: 'UI/UX Design', slug: 'ui-ux-design', shortDescription: 'Beautiful, intuitive user interfaces that delight your customers.', fullDescription: 'Great design is the foundation of great software. Our designers create wireframes, prototypes, and pixel-perfect designs that are both beautiful and functional.', icon: 'FaPalette', features: ['Wireframing', 'Prototyping', 'Brand Identity', 'Design Systems', 'User Research', 'Usability Testing'], technologies: ['Figma', 'Adobe XD', 'Illustrator', 'Photoshop', 'Framer', 'InVision'], priceRange: 'Starting from Rs.10,000', deliveryTime: '1-3 weeks', category: 'Design', order: 5 },
  { title: 'Digital Marketing & SEO', slug: 'digital-marketing-seo', shortDescription: 'Grow your online presence with data-driven marketing strategies.', fullDescription: 'We help businesses grow online through SEO, social media marketing, PPC campaigns, and content strategy. Our data-driven approach ensures maximum ROI.', icon: 'FaChartLine', features: ['SEO Optimization', 'Social Media Marketing', 'PPC Campaigns', 'Content Strategy', 'Email Marketing', 'Analytics & Reporting'], technologies: ['Google Ads', 'Meta Ads', 'SEMrush', 'Google Analytics', 'Mailchimp', 'HubSpot'], priceRange: 'Starting from Rs.8,000/month', deliveryTime: 'Ongoing', category: 'Marketing', order: 6 },
  { title: 'Cybersecurity', slug: 'cybersecurity', shortDescription: 'Protect your business with enterprise-grade security solutions.', fullDescription: 'Cybersecurity threats are evolving. We provide comprehensive security audits, penetration testing, and ongoing monitoring to keep your data and systems safe.', icon: 'FaShieldAlt', features: ['Security Audits', 'Penetration Testing', 'SSL & Encryption', 'Firewall Setup', 'VAPT', 'Compliance (GDPR/ISO)'], technologies: ['Kali Linux', 'Burp Suite', 'Nessus', 'Metasploit', 'Wireshark', 'OWASP'], priceRange: 'Starting from Rs.30,000', deliveryTime: '1-2 weeks', category: 'Security', order: 7 },
  { title: 'IT Consulting', slug: 'it-consulting', shortDescription: 'Expert technology consulting to help your business grow smarter.', fullDescription: 'Not sure which technology stack to choose? Our experienced consultants provide strategic technology advice, architecture reviews, and digital transformation roadmaps.', icon: 'FaLightbulb', features: ['Tech Stack Advisory', 'Architecture Review', 'Digital Transformation', 'Project Management', 'Team Augmentation', 'Cost Optimization'], technologies: ['Various', 'Agile', 'Scrum', 'JIRA', 'Confluence', 'Slack'], priceRange: 'Starting from Rs.5,000/hour', deliveryTime: 'Flexible', category: 'Consulting', order: 8 }
];

const products = [
  { name: 'Wooden Building Blocks Set', description: 'Premium quality wooden building blocks set with 50 colorful pieces. Perfect for developing motor skills and creativity in kids aged 2-6 years.', price: 799, originalPrice: 1200, category: 'Toys', ageGroup: '2-6 years', images: ['https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=500'], stock: 50, rating: 4.5, numReviews: 28, featured: true, badge: 'Best Seller' },
  { name: 'Kids Science Kit', description: 'Fun and educational science experiment kit with 30+ experiments. Encourages curiosity and STEM learning for kids aged 8-14 years.', price: 1299, originalPrice: 1799, category: 'Educational', ageGroup: '8-14 years', images: ['https://images.unsplash.com/photo-1532094349884-543559285d36?w=500'], stock: 30, rating: 4.8, numReviews: 45, featured: true, badge: 'Top Rated' },
  { name: 'Remote Control Car', description: 'High-speed RC car with 2.4GHz remote control. Rechargeable battery, all-terrain wheels, up to 30km/h speed. For kids aged 6+ years.', price: 1999, originalPrice: 2999, category: 'Toys', ageGroup: '6+ years', images: ['https://images.unsplash.com/photo-1594787317304-f6962c1b1328?w=500'], stock: 25, rating: 4.6, numReviews: 62, featured: true, badge: 'Sale' },
  { name: 'Children Story Books Set (10 Books)', description: 'Beautifully illustrated collection of 10 classic and modern children story books. Perfect for bedtime reading, ages 4-10 years.', price: 599, originalPrice: 900, category: 'Books', ageGroup: '4-10 years', images: ['https://images.unsplash.com/photo-1512820790803-83ca734da794?w=500'], stock: 100, rating: 4.7, numReviews: 89, featured: true, badge: 'New' },
  { name: 'Art & Craft Mega Kit', description: 'Complete art kit with 200+ pieces including crayons, watercolors, sketch pens, clay, and craft materials. For ages 4-12 years.', price: 899, originalPrice: 1400, category: 'Art & Craft', ageGroup: '4-12 years', images: ['https://images.unsplash.com/photo-1560762484-813fc97650a0?w=500'], stock: 40, rating: 4.4, numReviews: 34, featured: false, badge: 'Sale' },
  { name: 'Kids Cricket Set', description: 'Junior cricket set including bat, ball, stumps, and protective pads. Perfect starter kit for budding cricketers aged 7-14 years.', price: 1199, originalPrice: 1699, category: 'Sports', ageGroup: '7-14 years', images: ['https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=500'], stock: 35, rating: 4.3, numReviews: 21, featured: false },
  { name: 'Kids Learning Laptop', description: 'Educational toy laptop with 80+ learning activities including alphabet, numbers, music, and problem-solving games. Ages 3-8 years.', price: 1499, originalPrice: 2200, category: 'Electronics', ageGroup: '3-8 years', images: ['https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=500'], stock: 20, rating: 4.5, numReviews: 18, featured: true, badge: 'New' },
  { name: 'Kids Summer Wear Pack (3 Sets)', description: 'Comfortable and vibrant summer clothing set for kids. Made from 100% cotton, machine washable. Available in sizes 2-10 years.', price: 699, originalPrice: 1100, category: 'Clothing', ageGroup: '2-10 years', images: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=500'], stock: 60, rating: 4.2, numReviews: 41, featured: false },
  { name: 'Magnetic Drawing Board', description: 'Erasable colorful magnetic drawing board with stamp set. Kids can draw and erase endlessly. Great for travel. Ages 3+ years.', price: 449, originalPrice: 699, category: 'Art & Craft', ageGroup: '3+ years', images: ['https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=500'], stock: 75, rating: 4.6, numReviews: 56, featured: false, badge: 'Best Seller' },
  { name: 'Building Bricks 500pc', description: 'Compatible building bricks set with 500 pieces in multiple colors. Build anything you imagine! Safe, non-toxic. Ages 5+ years.', price: 999, originalPrice: 1599, category: 'Toys', ageGroup: '5+ years', images: ['https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=500'], stock: 45, rating: 4.8, numReviews: 73, featured: true, badge: 'Top Rated' },
  { name: 'Kids Yoga Mat Set', description: 'Fun animal-printed yoga mat with illustrated exercise guide for kids. Promotes fitness and mindfulness. Ages 4-12 years.', price: 549, originalPrice: 799, category: 'Sports', ageGroup: '4-12 years', images: ['https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500'], stock: 30, rating: 4.3, numReviews: 15, featured: false },
  { name: 'Kids Encyclopedia Bundle (5 Books)', description: 'Comprehensive encyclopedia set covering Science, History, Animals, Space, and Technology. For curious minds aged 8-15 years.', price: 1099, originalPrice: 1599, category: 'Books', ageGroup: '8-15 years', images: ['https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=500'], stock: 55, rating: 4.9, numReviews: 38, featured: false, badge: 'New' }
];

async function seed() {
  try {
    await mongoose.connect(MONGO_URI);
    console.log('Connected to MongoDB...');
    await Service.deleteMany({});
    await Product.deleteMany({});
    console.log('Cleared existing data...');
    await Service.insertMany(services);
    console.log('Seeded ' + services.length + ' services');
    await Product.insertMany(products);
    console.log('Seeded ' + products.length + ' products');
    console.log('Database seeded successfully!');
    process.exit(0);
  } catch (err) {
    console.error('Seeding error:', err.message);
    process.exit(1);
  }
}

seed();
